### ISSUE TITLE
Misaligned 'send' button on Firefox

### ISSUE THREAD

**Issue by paulwongx** [bedimcode/responsive-landing-page-christmas#1]
Thanks again for the great content and awesome design! 

For some reason, when viewing on Firefox on screen sizes 576px to ~920px, the button in the .send section that should submit the email gets mispositioned. It ends up showing up center aligned on the right border of the .send__direction container. This is fine on Chrome though. 

I double checked to make sure the html and css is the same and I didn't mistype something.

Do you get the same issues / is it the width setting that needs a special -moz prefix? I can't seem to figure out why...

Screenshot: https://ibb.co/N9JvL5D

Thanks. Again, thanks for your great code walkthrough and keep up the great content!

**Comment by bedimcode** [comment]
I answered you on YouTube, thanks for the observation, I will be more
careful in my future projects. Greetings and success.
